### ISSUE TITLE
Imagekit Uploads are Flipping Height and Width of Certain Images

### ISSUE THREAD

**Issue by choudlet** [imagekit-developer/imagekit-nodejs#40]
Hi! I'm seeing an issue with imagekit uploads that I am struggling to get to the bottom of. On calling the imagekit API with the following params:

`imagekit.upload({
      file: this.file,
      fileName: '${Date.now()}_tl',
    });`

I'm seeing this specific file (and other files that have been flagged by our users) ![IMG_9604](https://user-images.githubusercontent.com/12239288/167153740-3039c8a1-5b46-41d4-bab4-4b4ad8f064ad.jpg) being distorted and having the width and height switched. When I decode the base64 string I'm sending for the file it looks totally ok. 

Here's the chain of events I am seeing in the browser which highlights this error:

<img width="390" alt="Screen Shot 2022-05-06 at 8 36 46 AM" src="https://user-images.githubusercontent.com/12239288/167154974-3d4942ae-c7fa-43d9-98fc-f7da9c2be246.png">

The image in the browser (when I instantiate it from window.URL.createObjectURL(file : File)) has the correct width and height. The response from imagekit is what is flipping them. We then use those values for some custom resizing logic which are then incorrect. 

Do you have any ideas or tips on how to avoid this error or are there any other things we need to do to avoid this?

**Comment by imagekitio** [comment]
It is due to the presence of `Orientation` metadata in the image file. ImageKit will auto-rotate the image when the browser requests it based on your account settings. However, the upload API returns the dimension as it is. You can pass a parameter `responseField: metadata` in the upload API request to get actual metadata and then read the rotation value and implement the correct logic. The structure of metadata looks like this - https://docs.imagekit.io/api-reference/metadata-api#metadata-object-structure

This issue is related to API and not the SDK. If you have any further questions, request you to please raise a ticket on support@imagekit.io
