### ISSUE TITLE
Idea: Allow fetching, modifying and deleting of file by url

### ISSUE THREAD

**Issue by gregg-cbs** [imagekit-developer/imagekit-nodejs#52]
Hey,

Love imagekit! Got up and running in minutes.

I am however facing an issue, I cannot seem to get a file or delete a file by url. I do not store the file_id and I do not particularly want to.

Listing all images to then filter them by url just to get the id seems a waste of querying.

At the moment you have this:
```javascript
imagekit.getFileDetails("file_id", function(error, result) {});
imagekit.deleteFile("file_id", function(error, result) {});
```

Can we not have this? Seeing as urls are unique and most people store urls.
```javascript
imagekit.getFileDetails("file_url", function(error, result) {});
imagekit.deleteFile("file_url", function(error, result) {});

// for backwards compatibility
imagekit.getFileDetails({url: ""}, function(error, result) {});
imagekit.deleteFile({url: ""}, function(error, result) {});

// and still support id
imagekit.getFileDetails({id: ""}, function(error, result) {});
// and backwards compatibility
imagekit.getFileDetails("file_id", function(error, result) {});
```

**Comment by imagekitio** [comment]
Thanks for the suggestion @gregg-cbs. This will require changes in the backend API as this SDK is just a wrapper. Please drop a message to support@imagekit.io once from your registered email address and we can discuss ideas there. I will forward this feedback to the team. 
Since this is not specific to this SDK, I am closing this issue.
