### ISSUE TITLE
Your request contains invalid expire parameter. Expire parameter should be a Unix time in less than 1 hour into the future.

### ISSUE THREAD

**Issue by Cuantico** [imagekit-developer/imagekit-nodejs#8]
after a while Node server returns the following:
Your request contains invalid expire parameter. Expire parameter should be a Unix time in less than 1 hour into the future.

**Comment by imagekitio** [comment]
The problem seems to be on the front end side and not this SDK. We will be happy to help you with this, please email us on support@imagekit.io.

**Comment by olufemioyedepo** [comment]
Even after manually generating a UNIX timestamp, the error still persist.

**Comment by imagekitio** [comment]
Hey, can you please send the request information on support@imagekit.io. We will be able to help you there as this issue is not related to this SDK.

Also, I can assure you that the upload API (not related to this SDK) and token generation logic (related to this SDK) is fine. Because we use the exact same upload API in our media library and this SDK in backend for generating tokens and signature.
